-- TrustMD Email Tracking Schema
-- Add email logging and tracking tables for Resend integration

-- Create email logs table for tracking all email communications
CREATE TABLE IF NOT EXISTS email_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    type TEXT NOT NULL CHECK (type IN (
        'single', 'bulk', 'welcome', 'password_reset', 'email_verification',
        'subscription_confirmation', 'payment_failed', 'subscription_cancelled',
        'compliance_reminder', 'document_upload', 'security_alert', 'custom'
    )),
    recipients TEXT[] NOT NULL,
    subject TEXT NOT NULL,
    template TEXT,
    status TEXT NOT NULL CHECK (status IN ('sent', 'failed', 'partial', 'pending')),
    message_id TEXT,
    error TEXT,
    success_count INTEGER DEFAULT 0,
    failure_count INTEGER DEFAULT 0,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create email templates table for managing reusable email templates
CREATE TABLE IF NOT EXISTS email_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    display_name TEXT NOT NULL,
    description TEXT,
    subject_template TEXT NOT NULL,
    html_template TEXT,
    text_template TEXT,
    variables JSONB DEFAULT '{}',
    is_active BOOLEAN DEFAULT true,
    is_system BOOLEAN DEFAULT false,
    created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(tenant_id, name)
);

-- Create email preferences table for user email settings
CREATE TABLE IF NOT EXISTS email_preferences (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    email_type TEXT NOT NULL CHECK (email_type IN (
        'marketing', 'transactional', 'compliance', 'billing', 'security',
        'notifications', 'reminders', 'updates'
    )),
    is_enabled BOOLEAN DEFAULT true,
    frequency TEXT DEFAULT 'immediate' CHECK (frequency IN (
        'immediate', 'daily', 'weekly', 'monthly', 'never'
    )),
    last_sent_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(tenant_id, user_id, email_type)
);

-- Create email delivery events table for tracking delivery status
CREATE TABLE IF NOT EXISTS email_delivery_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email_log_id UUID REFERENCES email_logs(id) ON DELETE CASCADE,
    recipient TEXT NOT NULL,
    event_type TEXT NOT NULL CHECK (event_type IN (
        'sent', 'delivered', 'opened', 'clicked', 'bounced', 'complained', 'unsubscribed'
    )),
    event_timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    event_data JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add email preferences to existing users table
ALTER TABLE users 
ADD COLUMN email_preferences JSONB DEFAULT '{"marketing": false, "transactional": true, "compliance": true, "billing": true, "security": true, "notifications": true, "reminders": true, "updates": false}',
ADD COLUMN email_verified BOOLEAN DEFAULT false,
ADD COLUMN email_verification_token TEXT,
ADD COLUMN email_verification_expires_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN last_email_sent_at TIMESTAMP WITH TIME ZONE;

-- Add email settings to tenants table
ALTER TABLE tenants 
ADD COLUMN email_settings JSONB DEFAULT '{"from_name": "TrustMD", "reply_to": null, "bcc_emails": [], "custom_headers": {}}',
ADD COLUMN email_quota INTEGER DEFAULT 1000,
ADD COLUMN email_usage INTEGER DEFAULT 0,
ADD COLUMN email_quota_reset_date TIMESTAMP WITH TIME ZONE DEFAULT (DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month');

-- Insert default email templates
INSERT INTO email_templates (name, display_name, description, subject_template, html_template, text_template, variables, is_system, is_active) VALUES
(
    'welcome',
    'Welcome Email',
    'Sent to new users when they register',
    'Welcome to TrustMD - Your Compliance Journey Starts Here',
    NULL, -- Will be generated by EmailService
    NULL, -- Will be generated by EmailService
    '{"user_name": "string", "tenant_name": "string", "login_url": "string"}',
    true,
    true
),
(
    'password_reset',
    'Password Reset',
    'Sent when user requests password reset',
    'Reset Your TrustMD Password',
    NULL,
    NULL,
    '{"user_name": "string", "reset_url": "string"}',
    true,
    true
),
(
    'email_verification',
    'Email Verification',
    'Sent to verify user email address',
    'Verify Your TrustMD Email Address',
    NULL,
    NULL,
    '{"user_name": "string", "verification_url": "string"}',
    true,
    true
),
(
    'subscription_confirmation',
    'Subscription Confirmation',
    'Sent when subscription is activated',
    'TrustMD Subscription Confirmed',
    NULL,
    NULL,
    '{"user_name": "string", "tenant_name": "string", "plan_name": "string", "price": "string", "interval": "string"}',
    true,
    true
),
(
    'payment_failed',
    'Payment Failed',
    'Sent when payment fails',
    'Payment Failed - Action Required for TrustMD',
    NULL,
    NULL,
    '{"user_name": "string", "tenant_name": "string", "amount": "string", "date": "string"}',
    true,
    true
),
(
    'subscription_cancelled',
    'Subscription Cancelled',
    'Sent when subscription is cancelled',
    'TrustMD Subscription Cancelled',
    NULL,
    NULL,
    '{"user_name": "string", "tenant_name": "string", "plan_name": "string", "end_date": "string"}',
    true,
    true
),
(
    'compliance_reminder',
    'Compliance Reminder',
    'Sent for compliance task reminders',
    'Compliance Reminder - Action Required',
    NULL,
    NULL,
    '{"user_name": "string", "tenant_name": "string", "compliance_items": "array"}',
    true,
    true
),
(
    'document_upload',
    'Document Upload',
    'Sent when documents are uploaded',
    'Document Uploaded to TrustMD',
    NULL,
    NULL,
    '{"user_name": "string", "tenant_name": "string", "document": "object"}',
    true,
    true
),
(
    'security_alert',
    'Security Alert',
    'Sent for security events',
    'Security Alert - TrustMD Account Activity',
    NULL,
    NULL,
    '{"user_name": "string", "tenant_name": "string", "alert_details": "object"}',
    true,
    true
) ON CONFLICT (name) DO NOTHING;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_email_logs_tenant_id ON email_logs(tenant_id);
CREATE INDEX IF NOT EXISTS idx_email_logs_user_id ON email_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_email_logs_type ON email_logs(type);
CREATE INDEX IF NOT EXISTS idx_email_logs_status ON email_logs(status);
CREATE INDEX IF NOT EXISTS idx_email_logs_created_at ON email_logs(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_email_templates_tenant_id ON email_templates(tenant_id);
CREATE INDEX IF NOT EXISTS idx_email_templates_name ON email_templates(name);
CREATE INDEX IF NOT EXISTS idx_email_templates_is_active ON email_templates(is_active);

CREATE INDEX IF NOT EXISTS idx_email_preferences_tenant_id ON email_preferences(tenant_id);
CREATE INDEX IF NOT EXISTS idx_email_preferences_user_id ON email_preferences(user_id);
CREATE INDEX IF NOT EXISTS idx_email_preferences_email_type ON email_preferences(email_type);

CREATE INDEX IF NOT EXISTS idx_email_delivery_events_email_log_id ON email_delivery_events(email_log_id);
CREATE INDEX IF NOT EXISTS idx_email_delivery_events_recipient ON email_delivery_events(recipient);
CREATE INDEX IF NOT EXISTS idx_email_delivery_events_event_type ON email_delivery_events(event_type);
CREATE INDEX IF NOT EXISTS idx_email_delivery_events_event_timestamp ON email_delivery_events(event_timestamp DESC);

-- Row Level Security for email tables
ALTER TABLE email_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_delivery_events ENABLE ROW LEVEL SECURITY;

-- RLS Policies for email_logs
CREATE POLICY "Users can view their tenant's email logs" ON email_logs
    FOR SELECT USING (auth.uid() IS NOT NULL AND tenant_id = current_setting('app.current_tenant_id')::UUID);

CREATE POLICY "Admins can manage email logs" ON email_logs
    FOR ALL USING (
        auth.uid() IS NOT NULL AND 
        tenant_id = current_setting('app.current_tenant_id')::UUID AND
        EXISTS (
            SELECT 1 FROM users 
            WHERE id = auth.uid() 
            AND tenant_id = current_setting('app.current_tenant_id')::UUID
            AND role = 'admin'
        )
    );

-- RLS Policies for email_templates
CREATE POLICY "Users can view their tenant's email templates" ON email_templates
    FOR SELECT USING (
        auth.uid() IS NOT NULL AND 
        (tenant_id = current_setting('app.current_tenant_id')::UUID OR is_system = true)
    );

CREATE POLICY "Admins can manage email templates" ON email_templates
    FOR ALL USING (
        auth.uid() IS NOT NULL AND 
        tenant_id = current_setting('app.current_tenant_id')::UUID AND
        EXISTS (
            SELECT 1 FROM users 
            WHERE id = auth.uid() 
            AND tenant_id = current_setting('app.current_tenant_id')::UUID
            AND role = 'admin'
        )
    );

-- RLS Policies for email_preferences
CREATE POLICY "Users can manage their own email preferences" ON email_preferences
    FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Admins can manage tenant email preferences" ON email_preferences
    FOR ALL USING (
        auth.uid() IS NOT NULL AND 
        tenant_id = current_setting('app.current_tenant_id')::UUID AND
        EXISTS (
            SELECT 1 FROM users 
            WHERE id = auth.uid() 
            AND tenant_id = current_setting('app.current_tenant_id')::UUID
            AND role = 'admin'
        )
    );

-- RLS Policies for email_delivery_events
CREATE POLICY "Users can view their tenant's email delivery events" ON email_delivery_events
    FOR SELECT USING (
        auth.uid() IS NOT NULL AND 
        email_log_id IN (
            SELECT id FROM email_logs 
            WHERE tenant_id = current_setting('app.current_tenant_id')::UUID
        )
    );

-- Function to update email quota usage
CREATE OR REPLACE FUNCTION update_email_quota_usage()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE tenants 
    SET email_usage = email_usage + 1,
        updated_at = NOW()
    WHERE id = NEW.tenant_id;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update email quota usage
CREATE TRIGGER update_email_quota_usage_trigger
    AFTER INSERT ON email_logs
    FOR EACH ROW
    WHEN (NEW.status = 'sent')
    EXECUTE FUNCTION update_email_quota_usage();

-- Function to reset monthly email quota
CREATE OR REPLACE FUNCTION reset_monthly_email_quota()
RETURNS TRIGGER AS $$
BEGIN
    NEW.email_usage = 0;
    NEW.email_quota_reset_date = DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month';
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to reset monthly email quota
CREATE TRIGGER reset_monthly_email_quota_trigger
    BEFORE UPDATE ON tenants
    FOR EACH ROW
    WHEN (OLD.email_quota_reset_date <= CURRENT_DATE)
    EXECUTE FUNCTION reset_monthly_email_quota();

-- Function to check email quota
CREATE OR REPLACE FUNCTION check_email_quota(p_tenant_id UUID)
RETURNS BOOLEAN AS $$
DECLARE
    quota_limit INTEGER;
    current_usage INTEGER;
    reset_date TIMESTAMP WITH TIME ZONE;
BEGIN
    SELECT email_quota, email_usage, email_quota_reset_date 
    INTO quota_limit, current_usage, reset_date
    FROM tenants 
    WHERE id = p_tenant_id;
    
    -- Reset quota if needed
    IF reset_date <= CURRENT_DATE THEN
        UPDATE tenants 
        SET email_usage = 0,
            email_quota_reset_date = DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month'
        WHERE id = p_tenant_id;
        
        current_usage := 0;
    END IF;
    
    RETURN current_usage < quota_limit;
END;
$$ LANGUAGE plpgsql;

-- Function to get email statistics
CREATE OR REPLACE FUNCTION get_email_statistics(p_tenant_id UUID, p_date_range TEXT DEFAULT '30')
RETURNS JSON AS $$
DECLARE
    result JSON;
BEGIN
    SELECT json_build_object(
        'total_sent', COUNT(*) FILTER (WHERE status = 'sent'),
        'total_failed', COUNT(*) FILTER (WHERE status = 'failed'),
        'total_partial', COUNT(*) FILTER (WHERE status = 'partial'),
        'most_used_type', (
            SELECT type FROM email_logs 
            WHERE tenant_id = p_tenant_id 
            AND created_at >= CURRENT_DATE - INTERVAL '1 ' || p_date_range
            GROUP BY type 
            ORDER BY COUNT(*) DESC 
            LIMIT 1
        ),
        'delivery_rate', ROUND(
            (COUNT(*) FILTER (WHERE status = 'sent')::FLOAT / NULLIF(COUNT(*), 0)) * 100, 2
        ),
        'quota_usage', (
            SELECT json_build_object(
                'used', email_usage,
                'limit', email_quota,
                'remaining', email_quota - email_usage,
                'reset_date', email_quota_reset_date
            )
            FROM tenants WHERE id = p_tenant_id
        )
    )
    INTO result
    FROM email_logs 
    WHERE tenant_id = p_tenant_id 
    AND created_at >= CURRENT_DATE - INTERVAL '1 ' || p_date_range;
    
    RETURN COALESCE(result, '{}'::json);
END;
$$ LANGUAGE plpgsql;

-- View for email analytics
CREATE OR REPLACE VIEW email_analytics AS
SELECT 
    tenant_id,
    DATE_TRUNC('day', created_at) as date,
    type,
    status,
    COUNT(*) as total_emails,
    COUNT(*) FILTER (WHERE status = 'sent') as sent_emails,
    COUNT(*) FILTER (WHERE status = 'failed') as failed_emails,
    COUNT(*) FILTER (WHERE status = 'partial') as partial_emails
FROM email_logs
WHERE created_at >= CURRENT_DATE - INTERVAL '90 days'
GROUP BY tenant_id, DATE_TRUNC('day', created_at), type, status
ORDER BY date DESC;

-- Grant permissions to authenticated users
GRANT SELECT, INSERT, UPDATE ON email_logs TO authenticated;
GRANT SELECT, INSERT, UPDATE ON email_templates TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON email_preferences TO authenticated;
GRANT SELECT, INSERT ON email_delivery_events TO authenticated;
GRANT SELECT ON email_analytics TO authenticated;
GRANT EXECUTE ON FUNCTION check_email_quota(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION get_email_statistics(UUID, TEXT) TO authenticated;
